version: 2
jobs:
  pr_title_validations:
    docker:
      - image: circleci/ruby:2.5.5-browsers
    steps:
      - run:
          name: validate PR name starts with issue fixed (ex. #234)     
          command: ruby ./scripts/check_pr_name.rb
  unit_test:
    docker:
      - image: circleci/ruby:2.5.5-browsers
    steps:
      - checkout
      - run:
          name: validate PR name starts with issue fixed (ex. #234)     
          command: ruby ./scripts/check_pr_name.rb
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Bundle install
          command: bundle check || bundle install
      - run:
          name: Rubocop lint
          command: bundle exec rubocop -D
      - run:
          name: Rspec tests
          command: bundle exec rspec --color --require spec_helper spec
      - run:
          name: Duplicate rule check
          command: bundle exec ./bin/cfn_nag_rules
  end_to_end_test:
    docker:
      - image: circleci/ruby:2.5.5-browsers
    steps:
      - checkout
      - run:
          name: install cfn_nag-0.0.01 locally, rspec, pull sample templates, rspec test
          command: bash ./scripts/setup_and_run_end_to_end_tests.sh
  publish:
    docker:
      - image: circleci/ruby:2.5.5-browsers
    steps:
      - checkout
      - run:
          name: Bundle install
          command: bundle check || bundle install
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Publish gem
          command: bash ./scripts/publish.sh

workflows:
  version: 2
  test-and-publish:
    jobs:
      - unit_test
      - end_to_end_test
      - publish:
          requires:
            - unit_test
            #- end_to_end_test
          filters:
            branches:
              only: master
